-- Insert 100 entries into the "Publications" table
INSERT INTO "public"."Publications" ("title", "summary", "can_read")
VALUES
    ('The Art of Programming', 'A comprehensive guide to programming languages and best practices.', true),
    ('Data Science Essentials', 'Learn the fundamentals of data science and machine learning.', false),
    ('Cooking Adventures', 'Explore the world of culinary delights with this cookbook.', true),
    ('History Uncovered', 'Discover hidden historical events and their impact on the present.', false),
    ('Traveler\'s Diary', 'A traveler\'s personal journey to the most exotic destinations.', true),
    ('Financial Mastery', 'Achieve financial success and independence with expert advice.', false),
    ('Science and Technology Trends', 'Stay updated with the latest advancements in science and tech.', true),
    ('Mystery Tales', 'Solve thrilling mysteries and puzzles in this gripping novel.', false),
    ('Health and Wellness', 'Take charge of your health with tips for a balanced lifestyle.', true),
    ('Nature's Wonders', 'Explore the beauty and wonders of the natural world.', false),
    ('Artistic Creations', 'Admire and understand the masterpieces of famous artists.', true),
    ('Business Strategies', 'Strategies for entrepreneurs and business leaders.', false),
    ('Space Odyssey', 'Embark on a journey through the cosmos and beyond.', true),
    ('Fictional Escapes', 'Dive into imaginary worlds and experience epic adventures.', false),
    ('Travel Hacks', 'Travel tips and hacks for the modern explorer.', true),
    ('Financial Insights', 'Unlock the secrets to financial success and wealth accumulation.', false),
    ('Healthy Living', 'Achieve a healthy lifestyle with proven methods and practices.', true),
    ('Wildlife Encounters', 'Get up close and personal with the world\'s most amazing wildlife.', false),
    ('Art in Motion', 'Explore the dynamic world of contemporary art and artists.', true),
    ('Leadership Essentials', 'Become an effective leader with leadership principles and techniques.', false),
    ('Science Marvels', 'Marvel at the wonders of scientific discoveries and innovations.', true),
    ('Fantasy Realms', 'Enter enchanting realms filled with mythical creatures and magic.', false),
    ('Gourmet Delights', 'Indulge in gourmet dishes and culinary extravagance.', true),
    ('Financial Wisdom', 'Wisdom and strategies for financial prosperity and security.', false),
    ('Fitness and Well-Being', 'Achieve physical fitness and mental well-being with expert guidance.', true),
    ('Journey to the Amazon', 'Explore the Amazon rainforest and its unique biodiversity.', false),
    ('Modern Artistry', 'Discover modern art forms and their impact on culture and society.', true),
    ('Startup Success', 'A guide to launching and growing successful startups.', false),
    ('Astronomy Wonders', 'Explore the universe and the mysteries of the cosmos.', true),
    ('Epic Adventures', 'Embark on epic adventures with heroes and heroines of fantasy worlds.', false),
    ('Culinary Adventures', 'Embark on culinary adventures from around the globe.', true),
    ('Investment Strategies', 'Investment strategies for long-term financial growth.', false),
    ('Mindful Living', 'Achieve mindfulness and inner peace through meditation and awareness.', true),
    ('Safari Expedition', 'Experience the thrill of a safari expedition in Africa.', false),
    ('Contemporary Artists', 'Profiles of influential contemporary artists and their works.', true),
    ('Management Mastery', 'Master the art of effective management and leadership.', false),
    ('Space Exploration', 'The latest developments in space exploration and discoveries.', true),
    ('Mystical Journeys', 'Journey through mystical realms filled with magic and wonder.', false),
    ('World of Spices', 'Discover the diverse and flavorful world of spices and seasonings.', true),
    ('Real Estate Investments', 'Strategies for successful real estate investments and property management.', false),
    ('Yoga and Wellness', 'Achieve physical and mental wellness through yoga and holistic practices.', true),
    ('Underwater Adventures', 'Dive into the depths of the ocean and explore its hidden treasures.', false),
    ('Renaissance Art', 'Explore the art and culture of the Renaissance period.', true),
    ('Corporate Leadership', 'Leadership principles for corporate executives and managers.', false),
    ('Planets and Stars', 'Journey to distant planets and stars in the cosmos.', true),
    ('Fantasy Quests', 'Embark on quests filled with magic, creatures, and epic battles.', false),
    ('Taste of Italy', 'Savor the flavors of Italy with delicious recipes and culinary tales.', true),
    ('Financial Independence', 'Strategies for achieving financial independence and early retirement.', false),
    ('Mindful Practices', 'Incorporate mindfulness into daily life for mental and emotional well-being.', true),
    ('Amazon Wildlife', 'Discover the incredible wildlife of the Amazon rainforest.', false),
    ('Contemporary Sculpture', 'Explore the world of contemporary sculpture and its artistic expressions.', true),
    ('Business Innovation', 'Innovative strategies and practices for business growth and success.', false),
    ('Journey to Mars', 'The challenges and excitement of a mission to the Red Planet.', true),
    ('Mythical Realms', 'Enter mythical realms with gods, monsters, and legendary heroes.', false),
    ('Global Cuisine', 'Experience the diversity of global cuisine from street food to fine dining.', true),
    ('Stock Market Strategies', 'Strategies for investing in the stock market and building wealth.', false),
    ('Meditation and Peace', 'Find inner peace and tranquility through meditation and mindfulness.', true),
    ('Oceanic Exploration', 'Explore the mysteries of the ocean and its fascinating creatures.', false),
    ('Impressionist Art', 'Appreciate the beauty of Impressionist art and its impact on art history.', true),
    ('Entrepreneurial Success', 'Success stories and strategies of renowned entrepreneurs.', false),
    ('Exoplanets and Beyond', 'Discover distant exoplanets and the quest for extraterrestrial life.', true),
    ('Mythical Adventures', 'Embark on mythical adventures with legendary beings and quests.', false),
    ('Gourmet Desserts', 'Indulge in the world of gourmet desserts and sweet creations.', true),
    ('Retirement Planning', 'Plan for a comfortable and secure retirement with financial guidance.', false),
    ('Zen and Mindfulness', 'Achieve zen-like mindfulness through meditation and contemplation.', true),
    ('Arctic Expeditions', 'Explore the Arctic wilderness and its unique ecosystems.', false),
    ('Baroque Art', 'Appreciate the intricate beauty of Baroque art and architecture.', true),
    ('Leadership Excellence', 'Excellence in leadership through effective strategies and principles.', false),
    ('Black Holes and Galaxies', 'Journey to the darkest depths of space to study black holes and galaxies.', true),
    ('Epic Quests', 'Epic quests filled with heroic deeds, mythical creatures, and destiny.', false),
    ('Thai Cuisine', 'Experience the flavors of Thailand with authentic recipes and culinary stories.', true),
    ('Real Estate Wealth', 'Build wealth through real estate investments and property management.', false),
    ('Yoga and Serenity', 'Attain serenity and spiritual growth through yoga and meditation.', true),
    ('Great Barrier Reef', 'Explore the wonders of the Great Barrier Reef and its marine life.', false),
    ('Abstract Art', 'Interpret the abstract world of art and its diverse forms of expression.', true),
    ('Innovative Leadership', 'Lead with innovation and creativity in the ever-changing business landscape.', false),
    ('Interstellar Travel', 'The future of interstellar travel and exploration beyond our solar system.', true),
    ('Mythical Legends', 'Legends and myths of ancient cultures from around the world.', false),
    ('Sushi Delights', 'Savor the artistry of sushi and Japanese culinary traditions.', true),
    ('Cryptocurrency Investments', 'Investing in the world of cryptocurrencies and blockchain technology.', false),
    ('Mindful Living', 'Live mindfully and embrace holistic well-being through daily practices.', true),
    ('Great White Sharks', 'Dive into the world of great white sharks and their incredible lives.', false);
